CREATE TABLE IF NOT EXISTS app_content_pages (
 id INT AUTO_INCREMENT PRIMARY KEY, page_key VARCHAR(40) NOT NULL UNIQUE,
 title VARCHAR(160) NOT NULL, subtitle TEXT NOT NULL, sections JSON NOT NULL,
 updated_by_admin_id INT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (updated_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS support_threads (
 id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL UNIQUE,
 status VARCHAR(20) NOT NULL DEFAULT 'open', last_message_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS support_messages (
 id INT AUTO_INCREMENT PRIMARY KEY, thread_id INT NOT NULL, sender_type VARCHAR(20) NOT NULL,
 sender_admin_id INT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (thread_id) REFERENCES support_threads(id) ON DELETE CASCADE,
 FOREIGN KEY (sender_admin_id) REFERENCES admins(id) ON DELETE SET NULL
);
